name: Build on push

on:
  push:
    branches:
      - master

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: read
  security-events: read  # This is required to handle authentication to our artifact publishing API

jobs:
  build:
    uses: ./.github/workflows/build-yocto.yml
  schema-check:
    uses: ./.github/workflows/lava-schema-check.yml
  test:
    uses: ./.github/workflows/test.yml
    needs: [build, schema-check]
    secrets: inherit
    with:
      url: ${{ needs.build.outputs.artifacts_url }}
